config/routes.rb
Sh1nyV1::Application.routes.draw do
  
  get "html5_chart/index"

  get "admin/count_posts"

  root :to => "topics#list"
  

  match 'topics/list' => 'topics#list', :as => :topics
  match ':controller(/:action(/:id(.:format)))'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  serialize :upvoted_by

  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    list
    render('list')
  end

  def crossdomain
    render('crossdomain', :layout => false)
  end
  
  def list
      @topics = []
      @sort_by = params[:sort]
      if params[:search_string].to_s == ''
        if params[:sort] == 'popularity' 
          sql = 'select * from topics order by position ASC'
          @topics = ActiveRecord::Base.connection.execute(sql).to_a 
          @topics.uniq!
        else
          sql = 'select * from topics order by created_at DESC'
          @topics = ActiveRecord::Base.connection.execute(sql).to_a 
          @topics.uniq!
        end
        @next=params[:next].to_i+1
        @search_string = params[:search_string]
      else
        search_string = params[:search_string] 
        @search_string = search_string.gsub('%',' ')
        search_string.gsub!(' ','%')
        search_string = '%'+search_string+'%'
        if params[:sort] == 'popularity' 
          # for perfomance issues check: http://stackoverflow.com/questions/7005302/postgresql-how-to-make-not-case-sensitive-queries
          sql_search_in_subject = 'select * from topics where lower(subject) like lower(\''+search_string+'\') order by position ASC'
          sql_search_in_text = 'select * from topics where lower(text) like lower(\''+search_string+'\') order by position ASC'
          sql_search_in_comments = 'select * from topics where id in (select distinct topic_id from comments where lower(comment) like lower(\''+search_string+'\')) order by position ASC'
          sql_search_in_snippets = 'select * from topics where lower(snippet) like lower(\''+search_string+'\') order by created_at ASC'
          @topics = ActiveRecord::Base.connection.execute(sql_search_in_subject).to_a + ActiveRecord::Base.connection.execute(sql_search_in_snippets).to_a + ActiveRecord::Base.connection.execute(sql_search_in_text).to_a + ActiveRecord::Base.connection.execute(sql_search_in_comments).to_a
          @topics.uniq!
        else
          # for perfomance issues check: http://stackoverflow.com/questions/7005302/postgresql-how-to-make-not-case-sensitive-queries
          sql_search_in_subject = 'select * from topics where lower(subject) like lower(\''+search_string+'\') order by created_at DESC' 
          sql_search_in_text = 'select * from topics where lower(text) like lower(\''+search_string+'\') order by created_at DESC'
          sql_search_in_comments = 'select * from topics where id in (select distinct topic_id from comments where lower(comment) like lower(\''+search_string+'\')) order by created_at DESC'
          sql_search_in_snippets = 'select * from topics where lower(snippet) like lower(\''+search_string+'\') order by created_at DESC'
          @topics = ActiveRecord::Base.connection.execute(sql_search_in_subject).to_a + ActiveRecord::Base.connection.execute(sql_search_in_snippets).to_a + ActiveRecord::Base.connection.execute(sql_search_in_text).to_a + ActiveRecord::Base.connection.execute(sql_search_in_comments).to_a
          @topics.uniq!
        end
        @next=params[:next].to_i+1
      end
    end
  helper_method :list
  
  def chart
    @topics = Topic.order("topics.position DESC")
    @topics = @topics[0..10]
  end
  
  def show
    @topic = Topic.find(params[:id])
  end
  
  def new
#    if session[:user_id]
      @topic = Topic.new()
#    else
#      redirect_to(:action => 'login',:notice=>"You need to be logged in to submit.")
#    end
  end
  
  def edit
    @topic = Topic.find(params[:id])
  end
  
  def create_account
    @orig_from_comment = params[:orig_from_comment]
    @topic_id = params[:topic_id]
    new_user = User.create(params[:login],params[:password])
    if (new_user)
      if new_user.save
        session[:user_id] = new_user.id
        session[:login] = new_user.login      
        if params[:topic] != nil && (params[:comment] == '' || params[:comment] == nil)
          redirect_to(:action=>'create',:topic=>params[:topic],:notice=>'Thread added. User \''+new_user.login+'\' created succesfuly.')
          return
        end
        flash[:notice] = "User #{new_user.login} created."
        if params[:notice] == 'You need to be logged in to upvote.'
          if @orig_from_comment
            redirect_to(:controller=>'comments',:action=>'upvote_topic',:id=>@topic_id)
            return
          end
          if params[:topic_id] != nil
            redirect_to(:action=>:upvote,:id=>params[:topic_id])
            return
          else
            redirect_to(:action=>:upvote,:id=>params[:id])
            return
          end
        end        
        if params[:comment] != '' && params[:comment] != nil && params[:topic_id] != nil
          if !(params[:reply]) 
            redirect_to(:controller=>'comments',:action=>'create',:topic_id=>params[:topic_id],:comment=>params[:comment],:notice=>'Your comment has been published. User \''+new_user.login+'\' created successfuly.',:reply=>params[:reply])
            return
          else
            redirect_to(:controller=>'comments',:action=>'replied',:topic_id=>params[:topic_id],:comment=>params[:comment],:notice=>'Your comment has been published. User \''+new_user.login+'\' created successfuly.',:previous_id=>params[:previous_id])            
            return
        end
        end
        if params[:topic_id] == '' || params[:topic_id] == nil
          redirect_to(:action=>'list',:notice=>'User \''+new_user.login+'\' created successfuly. Start by adding your thread or post a comment!')
          return
        else
          if params[:comment] == nil || params[:comment] == ''
            redirect_to(:controller=>'comments',:action=>'index',:topic_id=>params[:topic_id])
            return
          end
          if params[:reply] == "false"
            redirect_to(:controller=>'comments',:action=>'create',:topic_id=>params[:topic_id],:comment=>params[:comment],:notice=>'Your comment has been published. User \''+new_user.login+'\' created successfuly.',:reply=>params[:reply])
            return
          else
            redirect_to(:controller=>'comments',:action=>'replied',:topic_id=>params[:topic_id],:comment=>params[:comment],:notice=>'Your comment has been published. User \''+new_user.login+'\' created successfuly.',:previous_id=>params[:previous_id])            
            return
          end
        end
      else
        notice = ''
        if params[:login].size<4 || params[:password].size<4
          notice="User creation failed. Minimum username and password length is 4 characters."
        else
          notice="The username already exists. Please choose a different one."
        end
#          redirect_to(:action=>'login',:notice=>notice,:topic_id=>params[:topic_id])     
            if params[:topic_id] != '' && params[:topic_id] != nil
              redirect_to(:controller=>'comments',:action=>'create_acc_and_post',:notice=>notice,:topic_id=>params[:topic_id],:comment=>params[:comment])
            else
              redirect_to(:action=>'login',:notice=>notice,:topic_id=>params[:topic_id])       
            end
          return
      end        
    end
  end
  
  def attempt_login
    @topic_id = params[:topic_id]
    @orig_from_comment = params[:orig_from_comment]
    authorized_user = User.authenticate(params[:login],params[:password])
    if (authorized_user)
      session[:user_id] = authorized_user.id
      session[:login] = authorized_user.login
      if params[:topic] != nil 
        redirect_to(:action=>'create',:topic=>params[:topic])
        return
      end
      if params[:notice] == 'You need to be logged in to upvote.'
        if @orig_from_comment
          redirect_to(:controller=>'comments',:action=>'upvote_topic',:id=>@topic_id)
          return
        end
        if params[:topic_id] != nil
          redirect_to(:action=>:upvote,:id=>params[:topic_id])
          return
        else
          redirect_to(:action=>:upvote,:id=>params[:id])
          return
        end
      end
      flash[:notice] = "You are now logged in."
      if @topic_id == '' || @topic_id == nil 
        redirect_to(:action => 'list',:notice=>"You are now logged in as \'"+params[:login]+'\'.')
        return
      else
        if params[:reply] == 'false'
          redirect_to(:controller=>'comments',:action=>'index',:topic_id=>@topic_id)
          return
        else
          redirect_to(:controller=>'comments',:action=>'replied',:comment=>params[:comment],:topic_id=>params[:topic_id],:previous_id=>params[:previous_id],:notice=>'You are now logged in. Your reply has been posted.')
          return
        end
      end
    else
      redirect_to(:action => 'login',:notice=>'Wrong username or password. Please try again.')
    end
  end
  
  def login
    flash[:notice] = params[:notice]
    @topic_id = params[:topic_id]
    @orig_from_comment = params[:comment]
  end
  
  def logout
    session[:user_id] = nil
    session[:login] = nil
    redirect_to(:action=>'list',:notice=>"You have been logged out.")
  end
  
  def upvote
    if session[:user_id] == nil    
      redirect_to(:controller=>'topics',:action=>'login',:notice=>'You need to be logged in to upvote.', :topic_id=>params[:id],:orig_from_comment=>@orig_from_comment)
      return
    end
    if (params[:id] != nil)
      @topic = Topic.find(params[:id])
    else
      @topic = Topic.find(params[:topic_id])
    end
    if session[:user_id] == @topic.user_id
      redirect_to(:action=>'list',:notice=>'You can\'t upvote your own Posts.')
      return
    end
    @topic.position = ((@topic.points+1)/(Time.now - @topic.created_at))
    @topic.points = @topic.points+1
    @topic.upvoted_by = ' ' if @topic.upvoted_by == nil
    @topic.upvoted_by << session[:login].to_s+' '
    @topic.save
    User.upvote(@topic.user_id)    
    @topics = Topic.order("topics.position DESC") 
    if @orig_from_comment == true
      redirect_to(:controller=>'comments',:action=>'index',:id=>params[:id])
    else

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<table summary="Topic from fields">
	<tr>
		<th>Title</th>
		<td><%= f.text_field(:subject) %></td>
	</tr>
	<tr>
		<th>URL</th>
		<td><%= f.url_field(:url) %></td>
	</tr>	
	<tr>
		<td colspan="2" align="middle"><span>-- OR --</span></td>
	</tr>
	<tr>
		<th>Text</th>
		<td><%= f.text_area(:text, :class=>"add_thread")%></td>
	</tr>	
</table>

app/views/topics/chart.html.erb
<% @page_title = "Live Gold Price & News" %>

<font size="14" face="myFont">sh<font color="red">1</font>ny<font size="5"   color="#black">&nbsp;&nbsp;&nbsp;&nbsp;Gold Price Chart -- </font><font size="5" color="#black">Live Gold Spot Prices<!--live gold price & chart--> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<!--Gold Price News, done right! --></font></font>
<div style="float:right" id="hello_world" class='listalista'>		
<%= link_to("chart",:action=>'chart') %>&nbsp;&nbsp;
<%= link_to("news",:action=>'list') %>&nbsp;&nbsp;
<%= link_to("videos",:action=>'videos') %>&nbsp;&nbsp;
<%= link_to("contact", :action=>'contact_c')%>
&nbsp;&nbsp;&nbsp;
</div>
<br>
</div>
<!--font size="3pt" align="center">This highly advanced customizable Chart updates gold prices automatically every 2 minutes in 26 currencies:<br-->

<!--font size="3.0" >The best interactive Gold Chart on the Web! Click for Forum & News below</font-->
<!--div class="fb-like" data-href="http://www.sh1ny.com" data-send="false" data-width="450" data-show-faces="false" data-font="lucida grande"></div><br

document.write('<iframe src="http://www.sh1ny.com:3001/alive5/Alive6_HighRes/" id="chartframe" name="chartframe" border=\'7\' frameborder=\'7\' width=\'980\' class="iframe" scrolling="no" frameborder="0" lwft="0" height="780" bordercolor="black" align="center"></iframe>');
exit;

-->
<style="text-align: right; background: #C4AD29;"></style>
<br>
<SCRIPT language="JavaScript">
<!--
if ((screen.width<=1280) && (screen.height<=800))
{
document.write('<iframe src="http://www.sh1ny.com:3001/alive5/Alive6_LowRes/" id="chartframe" name="chartframe" border=\'7\' frameborder=\'7\' width=\'650\' class="iframe" scrolling="no" frameborder="0" lwft="0" height="510" bordercolor="black" align="center"></iframe>');
exit;
}
if ((screen.width>=1600) && (screen.height>=1200))
{
	document.write('<iframe src="http://localhost:8400/alive5/Alive5-debug/Alive6.swf" id="chartframe" name="chartframe" border=\'7\' frameborder=\'7\' width=\'980\' class="iframe" scrolling="no" frameborder="0" lwft="0" height="780" bordercolor="black" align="center"></iframe>');
	exit;
}
document.write('<iframe src="http://www.sh1ny.com:3001/alive5/Alive6_MedRes/" id="chartframe" name="chartframe" border=\'7\' frameborder=\'7\' width=\'800\' class="iframe" scrolling="no" frameborder="0" lwft="0" height="610" bordercolor="black" align="center"></iframe>');
//-->
</SCRIPT>
<noscript>
	<iframe src="http://www.sh1ny.com:3001/alive5/Alive6_MedRes/" id="chartframe" name="chartframe" border=\'7\' frameborder=\'7\' width=\'800\' class="iframe" scrolling="no" frameborder="0" lwft="0" height="610" bordercolor="black" align="center"></iframe>
</noscript>
<br><br>
<font size = 2>
Latest News:<br>
<% @topics.each_with_index do |topic,i| %>
	<%= link_to(topic.subject,topic.url,:target=>'_blank')%>
	<br>
<% end %>
<%= link_to('>> more news in the News section...',:action=>'list',:target=>'_blank')%>
<br>

app/views/topics/chart_new.html.erb
<% @page_title = "Live Gold Price & News" %>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<font size="14" face="myFont">SH1NY CHART&nbsp;</font>
<font size="3.0" >The best interactive Gold Chart on the Web! Click for Forum & News below</font>
<!--div class="fb-like" data-href="http://www.sh1ny.com" data-send="false" data-width="450" data-show-faces="false" data-font="lucida grande"></div><br-->
<style="text-align: right; background: #C4AD29;"></style>
<br>
<SCRIPT language="JavaScript">
<!--
if ((screen.width>1024) && (screen.height>768)) 
{ 
	if ((screen.width<=1600) && (screen.height<1200))
	{	
document.write('<iframe src="http://www.sh1ny.com:3001/alive5/Alive6_MedRes/" id="chartframe" name="chartframe" border=\'7\' frameborder=\'7\' width=\'820\' class="iframe" scrolling="no" frameborder="0" lwft="0" height="640" bordercolor="black"></iframe>');
	}
}
if ((screen.width<=1024) && (screen.height<=768))
{
document.write('<iframe src="http://www.sh1ny.com:3001/alive5/Alive6_LowRes/" id="chartframe" name="chartframe" border=\'7\' frameborder=\'7\' width=\'650\' class="iframe" scrolling="no" frameborder="0" lwft="0" height="510" bordercolor="black"></iframe>');
}
if ((screen.width>=1600) && (screen.height>=1200))
{
document.write('<iframe src="http://www.sh1ny.com:3001/alive5/Alive6_HighRes/" id="chartframe" name="chartframe" border=\'7\' frameborder=\'7\' width=\'980\' class="iframe" scrolling="no" frameborder="0" lwft="0" height="780" bordercolor="black"></iframe>');
}
//-->
</SCRIPT>
<br><br>
<font size = 2>
<%= link_to("news & forum",:action=>'list') %><br>
<%= link_to("videos",:action=>'videos') %><br>
<%= link_to("contact us", :action=>'contact_c')%><br><br>

<br><br>
<script type="text/javascript" src="http://jj.revolvermaps.com/r.js"></script><script type="text/javascript">rm_f1st('0','220','true','false','000000','9yloocdij8w','true','ff0000');</script><noscript><applet codebase="http://rj.revolvermaps.com/j" code="core.RE" width="220" height="220" archive="g.jar"><param name="cabbase" value="g.cab" /><param name="r" value="true" /><param name="n" value="false" /><param name="i" value="9yloocdij8w" /><param name="m" value="0" /><param name="s" value="220" /><param name="c" value="ff0000" /><param name="v" value="true" /><param name="b" value="000000" /><param name="rfc" value="true" /></applet></noscript>

app/views/topics/contact_c.html.erb
<font size="14" face="myFont">sh<font color="red">1</font>ny<font color="#DEDEDE"> chart </font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font>
<div style="float:right" id="hello_world" class='listalista'>		
<%= link_to("chart",:action=>'chart') %>&nbsp;&nbsp;
<%= link_to("news",:action=>'list') %>&nbsp;&nbsp;
<%= link_to("videos",:action=>'videos') %>&nbsp;&nbsp;
<%= link_to("contact", :action=>'contact')%>
&nbsp;&nbsp;&nbsp;
</div>
<br>
<hr>
</div>

<% login = session[:login] %>
<% if login == nil then login="a" end %>
</div>
</font>

<% if !params[:notice].blank? %>
	<div class="notice">
		<%= params[:notice] %>
	</div>
<% end %>
<div class="back_link"><%= link_to("<< back", {:action=>'list'}, :class=>'back-link')%></div>
<div class="contact">
	<br>
	<h4>Contact Us:</h4>

	OnlyHedge LLC<br>
	e-mail: info@GoldPriceCafe.com<br>
</div>
<br>

app/views/topics/list.html.erb
<% @page_title = "Live Gold Chart & News" %>

<% per_page = 10 %>

<div id="content" class="box white container">
	<div class="top">
		<div class="top"><div class="top">&nbsp;</div></div>
	</div>
	<div class="middle">
		<div class="middle"><div class="middle">
			<div class="content">
				<h2>Gold Price News</h2>

				<div class="header">

					<div class="search_string">
						<div class="in">
							<div class="in">
								<form accept-charset="UTF-8" action="/topics/list" method="post" class="ajax_request">
									<%= text_field_tag :search_string, @search_string %>
									<%= submit_tag "Search" %>
								</form>
<!--
								<input name="string" type="text" />
								<input name="Search" type="submit"/>
-->
							</div>
						</div>
					</div>
					<% 
						sort_pop_class = 'ajax_request sort left'
						sort_date_class = 'ajax_request sort right'

						if @sort_by == 'popularity'
							sort_pop_class = sort_pop_class.concat(' current')
						else 
							sort_date_class = sort_date_class.concat(' current')
						end 
					%>
					<div class="sort">
						<span>Sort by</span>
						<span class="sort left">
						<%= link_to "Popularity", topics_path(:sort=>'popularity',:search_string=>@search_string), :class => sort_pop_class %></a></span>
						<span class="sort right">
						<%= link_to "Date", topics_path(:sort=>'date',:search_string=>@search_string), :class => sort_date_class %></span>
					</div>

					<div class="rightBox">
						<div class="in">
							<div class="in">
								<span class="add_thread"><%= link_to "add thread", {:action=>'new'}, :class => 'add_thread dialog', :rel=>"dialog_content" %></span>
							</div>
						</div>
					</div>
				</div>
				<table class="topics">
					<% if @topics.size > @next*per_page then end_step=@next*per_page else end_step=@topics.size end %>
					<% for i in @next*per_page-(per_page-1)..end_step do %>
					<% 
						topic = @topics[i-1]

						if defined?(topic.id)
							topic_id = topic.id
							topic_url = topic.url
							topic_user_id = topic.user_id
							topic_subject = topic.subject
							topic_points = topic.points
							topic_created_at = topic.created_at
							topic_upvoted_by = topic.upvoted_by
							topic_snippet = topic.snippet
							topic_text = topic.text
						else
							topic_id = topic["id"].to_i
							topic_url = topic["url"]
							topic_user_id = topic["user_id"].to_i
							topic_subject = topic["subject"]
							topic_points = topic["points"].to_i
							topic_created_at = topic["created_at"].to_datetime
							topic_upvoted_by = topic["upvoted_by"]
							topic_snippet = topic["snippet"]
							topic_text = topic["text"]
						end 
					%>
					<tr>	
						<td class="no"><span class="no"><%= i %></span></td>
						<td class="vote">
							<% if( session[:user_id] != nil && session[:user_id] != topic_user_id && !(topic_upvoted_by.include? session[:login] if topic_upvoted_by != nil)) %>
								<span class="vote"><%= link_to "upvote", {:action=>'upvote',:id=>topic_id}, :class => "vote ajax_request no_history" %></span>
								upvote
							<% end %>
							<% if (session[:user_id] == nil) %>
								<span class="vote"><%= link_to "upvote", {:action=>'upvote',:id=>topic_id}, :class => "vote ajax_request no_history" %></span>
								upvote
							<% end %>
						</td>
						<td class="topic">
							<h3 class="topic">
								<%= link_to topic_subject, {:controller=>'comments',:action=>'index',:topic_id=>topic_id,:sort=>@sort_by}, :class => "discuss ajax_request" %>
							</h3>
							<% if topic_snippet != nil %>
								<!--% t = topic_snippet.gsub(/\n/,' ') %-->
								<!--% t.gsub!('<p>',' ') %-->
								<!--% t.gsub!('</p>',' ') %-->
								<!--% t.gsub!('&nbsp;',' ') %-->
								<% t = sanitize(topic_snippet, :tags => %w(), :attributes => %w()) %>
								<span class="snippet"><%= if topic_snippet.size > 300 then t.slice(0,300)+'...' else t end %></span>
							<% end %>
							<span class="points"><%= tp=topic_points %> <% if tp==1 %> point <% else %> points <% end %></span>
							<span class="date">
							<% 
								@blob = ((DateTime.now.change(:offset=>"+0000").to_i - topic_created_at.strftime("%s").to_i)/60) 
								@text = "minutes ago"
								if @blob > 120 then @blob = @blob/60; @text="hours ago"; end
								if @blob > 48 && @text=="hours ago" then @blob = @blob/24; @text="days ago"; end
								if @blob > 730 && @text=="days ago" then @blob = @blob/365; @text="years ago"; end 
							%>
							<%= @blob %> <%= @text %>
							</span>
							<span class="by">by <%= User.where(:id => topic_user_id).first.login %></span>
						</td>
						<td class="comments_count">
							<%
								cs = Comment.where(:topic_id=>topic_id).size
								if cs <= 1 
									cs = cs.to_s.concat(" comment")
								else
									cs = cs.to_s.concat(" comments")
								end
							%>
							<%= link_to cs, {:controller=>'comments',:action=>'index',:topic_id=>topic_id,:sort=>@sort_by}, :class => "discuss ajax_request" %>
						</td>
						<td class="discuss">
							<span class="discuss"><%= link_to "discuss", {:controller=>'comments',:action=>'index',:topic_id=>topic_id,:sort=>@sort_by}, :class => "discuss ajax_request" %></span>
						</td>
						
						<% if (topic_user_id == session[:user_id] && cs.to_i < 2) || ( !session[:user_id].nil? && User.find(session[:user_id]).login == 'admin') %>
						<td class="edit" style="width:1px;">
							<span class="edit"><%= link_to "edit", {:controller=>'topics',:action=>'edit',:id=>topic_id,:sort=>@sort_by}, :class=>'dialog', :rel=>'dialog_content' %></span>
						</td>
						<td class="delete"
						    style="position:relative;
							width:1px;">
							<%= link_to "delete", '', :class=>"delete" %>
<div class="delete-box" style="display: none;">
									<a href="/topics/destroy/<%= topic_id %>/<%= @sort_by %>" rel="content" class="yes no_history ajax_request">Yes</a>
									<a href="#" class="no no_history">No</a>
								</div>
						</td>
						<% else %>
						<td style="width:1px;">&nbsp;</td>
						<td style="width:1px;">&nbsp;</td>
						<% end %>
					</tr>
					<% end %>
				</table>
				<div class="footer">

					<div class="pagination">
						<div class="step next">
						<% if @next>1 then %>
							<%= link_to "Previous page",{:action=>'list',:next=>@next.to_i-2,:sort=>@sort_by}, :class=>"ajax_request" %>
						<% end %>
						</div>

						<div class="pages">
							<% 
								i = @next
								total_pages = (@topics.size/per_page.to_f).ceil

								if total_pages < 9
									pages = total_pages
									i = 0
								else
									if i > (total_pages-5)
										pages = total_pages
										i = total_pages-8
										i=i-1
									else
										if i>5
											pages = i+4
											i = i-5 
										else 
											pages = 9
											i = 0
										end
									end
								end

								while i < pages 
									class_ = 'ajax_request'
									if( (@next.to_i - 1) == i )
										class_ = class_.concat(' current')
									end
									%>
							<%= link_to (i+1), {:action=>'list', :next=> i, :search_string=>@search_string,:sort=>@sort_by}, :class => class_ %>
							<% 
									i += 1; 
								end 
							%>

						</div>
						<div class="step previous">
						<% if @topics.size > @next*per_page then %>
							<%= link_to "Next page", {:action=>'list',:next=>@next, :search_string=>@search_string, :sort=>@sort_by}, :class=>"ajax_request" %>
						<% end %>
						</div>
					</div>

					<div class="rightBox">
						<div class="in">
							<div class="in">
								<span class="add_thread"><%= link_to "add thread", {:action=>'new'}, :class => 'add_thread dialog', :rel=>"dialog_content" %></span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div></div>
	</div>
<div class="bottom"><div class="bottom"><div class="bottom">&nbsp;</div></div></div>
</div>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  var pluginUrl = '//www.google-analytics.com/plugins/ga/inpage_linkid.js';
	  _gaq.push(['_require', 'inpage_linkid', pluginUrl]);
	  _gaq.push(['_setAccount', 'UA-31150857-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>